export const decks = [
  {
    title: "Blockbuster Movies",
    description:
      "Act out or describe iconic blockbuster films that made cinema history.",
    cards: [
      "Titanic",
      "Jurassic Park",
      "The Avengers",
      "Avatar",
      "Star Wars: A New Hope",
      "Inception",
      "The Lion King",
      "Forrest Gump",
      "The Dark Knight",
      "Back to the Future",
      "Jaws",
      "The Matrix",
      "Toy Story",
      "Frozen",
      "Harry Potter and the Sorcerer's Stone",
      "Finding Nemo",
      "The Godfather",
      "Pirates of the Caribbean",
      "E.T.",
      "Rocky",
      "Ghostbusters",
      "Home Alone",
      "Indiana Jones",
      "The Shawshank Redemption",
      "Iron Man",
      "The Lord of the Rings: Fellowship of the Ring",
      "The Hunger Games",
      "Black Panther",
      "Coco",
      "Wonder Woman",
      "Spider-Man",
      "The Incredibles",
      "Up",
      "Interstellar",
      "Shrek",
      "Beauty and the Beast",
      "Gladiator",
      "Terminator 2",
      "Die Hard",
      "Mad Max: Fury Road",
      "Pulp Fiction",
      "Guardians of the Galaxy",
      "Braveheart",
      "Men in Black",
      "Twilight",
      "Avatar: The Way of Water",
      "Deadpool",
      "The Fast and the Furious",
      "Aladdin",
      "WALL-E",
      "Zootopia",
      "The Silence of the Lambs",
      "Titanic",
      "Mission: Impossible",
      "Skyfall",
      "Casino Royale",
      "Monsters, Inc.",
      "Kung Fu Panda",
      "Moana",
      "Despicable Me",
      "Inside Out",
      "Aquaman",
      "Jurassic World",
      "Transformers",
      "Logan",
      "Dunkirk",
      "Parasite",
      "Joker",
      "Captain Marvel",
      "La La Land",
      "A Star is Born",
      "Thor: Ragnarok",
      "Venom",
      "Shazam!",
      "Mulan",
      "Star Wars: The Force Awakens",
      "Avengers: Endgame",
      "Avengers: Infinity War",
      "Star Wars: The Empire Strikes Back",
      "Harry Potter and the Deathly Hallows",
      "Ant-Man",
      "The Great Gatsby",
      "X-Men",
      "Fantastic Beasts",
      "The Revenant",
      "Frozen II",
      "Toy Story 3",
      "Jumanji",
      "King Kong",
      "The Hobbit",
      "Armageddon",
      "Twister",
      "The Departed",
      "Gravity",
      "300",
      "Spider-Man: No Way Home",
      "Doctor Strange",
      "Justice League",
      "Batman Begins",
      "Man of Steel",
      "Top Gun",
      "The Little Mermaid",
      "Raiders of the Lost Ark",
      "Star Trek",
      "Pacific Rim",
    ],
  },
  {
    title: "Harry Potter Universe",
    description:
      "Characters, spells, magical items, and locations from the wizarding world of Harry Potter.",
    cards: [
      "Harry Potter",
      "Hermione Granger",
      "Ron Weasley",
      "Albus Dumbledore",
      "Severus Snape",
      "Voldemort",
      "Sirius Black",
      "Draco Malfoy",
      "Dobby",
      "Hagrid",
      "Ginny Weasley",
      "Luna Lovegood",
      "Neville Longbottom",
      "Minerva McGonagall",
      "Lucius Malfoy",
      "Bellatrix Lestrange",
      "Fred Weasley",
      "George Weasley",
      "Cedric Diggory",
      "Cho Chang",
      "Dolores Umbridge",
      "Remus Lupin",
      "Nymphadora Tonks",
      "Arthur Weasley",
      "Molly Weasley",
      "Fawkes",
      "Nagini",
      "Basilisk",
      "Buckbeak",
      "Sorting Hat",
      "Elder Wand",
      "Invisibility Cloak",
      "Resurrection Stone",
      "Golden Snitch",
      "Nimbus 2000",
      "Firebolt",
      "Platform 9¾",
      "Diagon Alley",
      "Gringotts Bank",
      "Hogwarts Express",
      "Hogwarts Castle",
      "Forbidden Forest",
      "The Burrow",
      "Quidditch",
      "Polyjuice Potion",
      "Marauder's Map",
      "Patronus Charm",
      "Expelliarmus",
      "Avada Kedavra",
      "Expecto Patronum",
      "Lumos",
      "Wingardium Leviosa",
      "Sectumsempra",
      "Cruciatus Curse",
      "Imperius Curse",
      "Azkaban",
      "Death Eaters",
      "Dementors",
      "Goblet of Fire",
      "Triwizard Tournament",
      "Order of the Phoenix",
      "Mirror of Erised",
      "Room of Requirement",
      "Whomping Willow",
      "Pensieve",
      "Horcrux",
      "Chamber of Secrets",
      "Philosopher's Stone",
      "Time-Turner",
      "Butterbeer",
      "Chocolate Frog",
      "Floo Powder",
      "Knight Bus",
      "Mad-Eye Moody",
      "Gilderoy Lockhart",
      "Cornelius Fudge",
      "Kingsley Shacklebolt",
      "Peter Pettigrew",
      "Grawp",
      "Crookshanks",
      "Scabbers",
      "Hedwig",
      "Mandrake",
      "Thestral",
      "Veela",
      "Werewolf",
      "House-Elf",
      "Deathly Hallows",
      "Durmstrang",
      "Beauxbatons",
      "Godric Gryffindor",
      "Salazar Slytherin",
      "Rowena Ravenclaw",
      "Helga Hufflepuff",
      "Nearly Headless Nick",
      "Moaning Myrtle",
      "Filch",
      "Peeves",
    ],
  },
  {
    title: "Disney Classics",
    description:
      "Beloved characters, songs, and moments from classic Disney movies.",
    cards: [
      "Mickey Mouse",
      "Donald Duck",
      "Cinderella",
      "Snow White",
      "Ariel",
      "Simba",
      "Elsa",
      "Anna",
      "Belle",
      "Beast",
      "Peter Pan",
      "Tinker Bell",
      "Pinocchio",
      "Bambi",
      "Dumbo",
      "Aladdin",
      "Genie",
      "Mulan",
      "Pocahontas",
      "Rapunzel",
      "Sleeping Beauty",
      "Maleficent",
      "Cruella de Vil",
      "Woody",
      "Buzz Lightyear",
      "Timon",
      "Pumbaa",
      "Ursula",
      "Jasmine",
      "Prince Charming",
      "Tarzan",
      "Jane",
      "Alice in Wonderland",
      "Cheshire Cat",
      "Olaf",
      "Kristoff",
      "Moana",
      "Maui",
      "Lilo",
      "Stitch",
      "Goofy",
      "Pluto",
      "Chip 'n' Dale",
      "Scar",
      "Merida",
      "Sebastian",
      "Flounder",
      "Gaston",
      "Lumière",
      "Cogsworth",
      "Dory",
      "Nemo",
      "Marlin",
      "Lady",
      "Tramp",
      "101 Dalmatians",
      "Hercules",
      "Megara",
      "Robin Hood",
      "Winnie the Pooh",
      "Eeyore",
      "Piglet",
      "Tigger",
      "Baloo",
      "Mowgli",
      "King Louie",
      "Esmeralda",
      "Quasimodo",
      "Captain Hook",
      "Mary Poppins",
      "Baymax",
      "Joy",
      "Sadness",
      "Mike Wazowski",
      "Sully",
      "Mater",
      "Lightning McQueen",
      "Peter Pan's Shadow",
      "Thumper",
      "Jiminy Cricket",
      "Fairy Godmother",
      "Zazu",
      "Aurora",
      "Pocahontas",
      "Daisy Duck",
      "Flynn Rider",
      "Pascal",
      "Mother Gothel",
      "Prince Eric",
      "Flora, Fauna, and Merryweather",
      "The Seven Dwarfs",
      "The Incredibles",
      "Jack Skellington",
      "Oogie Boogie",
      "Kuzco",
      "Yzma",
      "Bolt",
      "Remy",
      "WALL-E",
      "EVE",
    ],
  },
  {
    title: "Marvel Heroes & Villains",
    description:
      "Superheroes and villains from the expansive Marvel Comics and Cinematic Universe.",
    cards: [
      "Iron Man",
      "Captain America",
      "Thor",
      "Hulk",
      "Black Widow",
      "Hawkeye",
      "Spider-Man",
      "Black Panther",
      "Doctor Strange",
      "Scarlet Witch",
      "Vision",
      "Captain Marvel",
      "Falcon",
      "Winter Soldier",
      "Ant-Man",
      "Wasp",
      "Star-Lord",
      "Gamora",
      "Rocket Raccoon",
      "Groot",
      "Drax",
      "Loki",
      "Thanos",
      "Ultron",
      "Green Goblin",
      "Doctor Octopus",
      "Venom",
      "Deadpool",
      "Daredevil",
      "Luke Cage",
      "Jessica Jones",
      "Iron Fist",
      "Kingpin",
      "Punisher",
      "Ghost Rider",
      "Magneto",
      "Professor X",
      "Jean Grey",
      "Cyclops",
      "Storm",
      "Mystique",
      "Nightcrawler",
      "Beast",
      "Quicksilver",
      "Silver Surfer",
      "Blade",
      "Shang-Chi",
      "Moon Knight",
      "She-Hulk",
      "Ms. Marvel",
      "War Machine",
      "Nebula",
      "Yondu",
      "Mantis",
      "Nick Fury",
      "Agent Coulson",
      "Red Skull",
      "Hydra Agent",
      "Ego",
      "The Collector",
      "Ronan the Accuser",
      "Killmonger",
      "Vulture",
      "Electro",
      "Sandman",
      "Rhino",
      "Carnage",
      "Morbius",
      "Sabretooth",
      "Juggernaut",
      "Apocalypse",
      "Cable",
      "Gambit",
      "Rogue",
      "Emma Frost",
      "Colossus",
      "Angel",
      "Iceman",
      "Polaris",
      "Black Cat",
      "Kraven the Hunter",
      "Taskmaster",
      "Dormammu",
      "Hela",
      "Surtur",
      "Crossbones",
      "Baron Zemo",
      "America Chavez",
      "Kate Bishop",
      "Agatha Harkness",
      "Namor",
      "Wong",
      "Shuri",
      "Okoye",
      "Abomination",
      "Adam Warlock",
      "MODOK",
      "Lady Sif",
      "Heimdall",
      "Howard the Duck",
    ],
  },
  {
    title: "90s Throwbacks",
    description:
      "Nostalgic references including music, TV shows, toys, and trends from the 1990s.",
    cards: [
      "Tamagotchi",
      "Spice Girls",
      "Blockbuster Video",
      "Friends",
      "Fresh Prince of Bel-Air",
      "Britney Spears",
      "Beanie Babies",
      "Pokemon",
      "Furbies",
      "Walkman",
      "Game Boy",
      "AOL Dial-Up",
      "Titanic",
      "Saved by the Bell",
      "The Macarena",
      "Sega Genesis",
      "Snap Bracelets",
      "The Lion King",
      "Jurassic Park",
      "Boy Meets World",
      "Nintendo 64",
      "Skip-It",
      "NSYNC",
      "Backstreet Boys",
      "MC Hammer",
      "Power Rangers",
      "Lisa Frank",
      "Clueless",
      "Super Soaker",
      "Slap Bracelets",
      "Full House",
      "Goosebumps",
      "Tickle Me Elmo",
      "Polly Pocket",
      "Discman",
      "The Simpsons",
      "Floppy Disks",
      "Sabrina the Teenage Witch",
      "TRL (Total Request Live)",
      "Dawson's Creek",
      "Pogs",
      "Space Jam",
      "MTV",
      "Baywatch",
      "Pulp Fiction",
      "Rollerblades",
      "Jumanji",
      "Home Alone",
      "Giga Pets",
      "Buffy the Vampire Slayer",
      "Nokia 3310",
      "Ring Pop",
      "Xena: Warrior Princess",
      "Mighty Ducks",
      "Slime",
      "Hip Hop Dance",
      "The X-Files",
      "Gel Pens",
      "The Matrix",
      "Scrunchies",
      "Cargo Pants",
      "Platform Shoes",
      "Surge Soda",
      "Clarissa Explains It All",
      "Animaniacs",
      "Hey Arnold!",
      "Doug",
      "Rocko's Modern Life",
      "Are You Afraid of the Dark?",
      "Mario Kart 64",
      "Windows 95",
      "Dunkaroos",
      "Dial-Up Internet",
      "Fanny Packs",
      "Yo-Yos",
      "Hacky Sack",
      "Reebok Pumps",
      "Cassette Tapes",
      "Grunge Music",
      "Doc Martens",
      "Trapper Keeper",
      "Waterbeds",
      "Pagers",
      "Air Jordans",
      "Laser Pointers",
      "Mortal Kombat",
      "Street Fighter",
      "Go-Gurt",
      "Baggy Jeans",
      "Sony PlayStation",
      "Easy-Bake Oven",
      "Lite-Brite",
      "Moon Shoes",
      "Teenage Mutant Ninja Turtles",
      "The Oregon Trail",
      "Lunchables",
      "Butterfly Clips",
      "Dance Dance Revolution",
      "Mr. Sketch Markers",
      "Nickelodeon Slime",
      "Inspector Gadget",
    ],
  },
  {
    title: "Animal Kingdom",
    description:
      "Animals of all shapes and sizes, from pets to wild beasts across the globe.",
    cards: [
      "Lion",
      "Elephant",
      "Tiger",
      "Giraffe",
      "Bear",
      "Wolf",
      "Rabbit",
      "Dog",
      "Cat",
      "Horse",
      "Kangaroo",
      "Panda",
      "Koala",
      "Dolphin",
      "Whale",
      "Shark",
      "Octopus",
      "Snake",
      "Lizard",
      "Frog",
      "Monkey",
      "Chimpanzee",
      "Gorilla",
      "Zebra",
      "Crocodile",
      "Alligator",
      "Hippopotamus",
      "Rhinoceros",
      "Cheetah",
      "Leopard",
      "Gazelle",
      "Deer",
      "Moose",
      "Camel",
      "Buffalo",
      "Fox",
      "Raccoon",
      "Owl",
      "Eagle",
      "Hawk",
      "Penguin",
      "Chicken",
      "Duck",
      "Goose",
      "Turkey",
      "Peacock",
      "Flamingo",
      "Parrot",
      "Hummingbird",
      "Woodpecker",
      "Ant",
      "Bee",
      "Butterfly",
      "Spider",
      "Ladybug",
      "Dragonfly",
      "Grasshopper",
      "Crab",
      "Lobster",
      "Jellyfish",
      "Starfish",
      "Sea Turtle",
      "Seahorse",
      "Otter",
      "Seal",
      "Walrus",
      "Bat",
      "Rat",
      "Mouse",
      "Hamster",
      "Guinea Pig",
      "Squirrel",
      "Porcupine",
      "Hedgehog",
      "Sloth",
      "Armadillo",
      "Badger",
      "Skunk",
      "Donkey",
      "Pig",
      "Cow",
      "Sheep",
      "Goat",
      "Llama",
      "Alpaca",
      "Ostrich",
      "Emu",
      "Platypus",
      "Salmon",
      "Tuna",
      "Goldfish",
      "Clownfish",
      "Pufferfish",
      "Swordfish",
      "Manta Ray",
      "Polar Bear",
      "Meerkat",
      "Hyena",
      "Jackal",
      "Wombat",
    ],
  },
  {
    title: "Iconic Celebrities",
    description:
      "Famous actors, singers, influencers, and personalities recognizable worldwide.",
    cards: [
      "Beyoncé",
      "Leonardo DiCaprio",
      "Taylor Swift",
      "Brad Pitt",
      "Oprah Winfrey",
      "Tom Cruise",
      "Angelina Jolie",
      "Ariana Grande",
      "Elon Musk",
      "Lady Gaga",
      "Dwayne Johnson",
      "Jennifer Aniston",
      "Johnny Depp",
      "Kanye West",
      "Kim Kardashian",
      "Morgan Freeman",
      "Emma Watson",
      "Chris Hemsworth",
      "Rihanna",
      "Justin Bieber",
      "Selena Gomez",
      "Cristiano Ronaldo",
      "Robert Downey Jr.",
      "Zendaya",
      "Will Smith",
      "Adele",
      "Ed Sheeran",
      "Meryl Streep",
      "Ryan Reynolds",
      "Keanu Reeves",
      "Jennifer Lopez",
      "Harry Styles",
      "Billie Eilish",
      "Drake",
      "Tom Hanks",
      "Scarlett Johansson",
      "Ellen DeGeneres",
      "George Clooney",
      "Miley Cyrus",
      "Hugh Jackman",
      "Samuel L. Jackson",
      "Sandra Bullock",
      "Natalie Portman",
      "Vin Diesel",
      "David Beckham",
      "Britney Spears",
      "Cardi B",
      "Shakira",
      "Daniel Radcliffe",
      "Katy Perry",
      "Chris Evans",
      "LeBron James",
      "Emma Stone",
      "Gal Gadot",
      "Barack Obama",
      "Michelle Obama",
      "Mark Zuckerberg",
      "Kylie Jenner",
      "Jennifer Lawrence",
      "Prince Harry",
      "Meghan Markle",
      "Stephen Curry",
      "Madonna",
      "Robert Pattinson",
      "Anne Hathaway",
      "Arnold Schwarzenegger",
      "Demi Lovato",
      "Bruno Mars",
      "Blake Lively",
      "Tom Holland",
      "Gordon Ramsay",
      "Liam Hemsworth",
      "Zac Efron",
      "Serena Williams",
      "Kendall Jenner",
      "Jason Momoa",
      "Chris Pratt",
      "Nicki Minaj",
      "Kate Middleton",
      "Ryan Gosling",
      "Celine Dion",
      "Jim Carrey",
      "Gigi Hadid",
      "Bella Hadid",
      "Matthew McConaughey",
      "Reese Witherspoon",
      "Harrison Ford",
      "Chadwick Boseman",
      "Viola Davis",
      "Kevin Hart",
      "Dolly Parton",
      "Lil Nas X",
      "Tyler Swift",
      "Post Malone",
      "Shawn Mendes",
      "Camila Cabello",
      "Paul Rudd",
      "Timothée Chalamet",
      "Millie Bobby Brown",
      "Pedro Pascal",
    ],
  },
  {
    title: "Video Game Legends",
    description:
      "Characters, game titles, and iconic elements from classic and contemporary video games.",
    cards: [
      "Mario",
      "Link",
      "Master Chief",
      "Lara Croft",
      "Pikachu",
      "Sonic the Hedgehog",
      "Pac-Man",
      "Donkey Kong",
      "Solid Snake",
      "Mega Man",
      "Kratos",
      "Samus Aran",
      "Nathan Drake",
      "Geralt of Rivia",
      "Princess Zelda",
      "Cloud Strife",
      "Spyro",
      "Crash Bandicoot",
      "Ezio Auditore",
      "Ryu (Street Fighter)",
      "Chun-Li",
      "Kirby",
      "Doom Slayer",
      "Joel (The Last of Us)",
      "Ellie (The Last of Us)",
      "Sackboy",
      "Fox McCloud",
      "Yoshi",
      "Bowser",
      "Princess Peach",
      "Captain Falcon",
      "Gordon Freeman",
      "Steve (Minecraft)",
      "Scorpion (Mortal Kombat)",
      "Sub-Zero",
      "Agent 47",
      "Tracer (Overwatch)",
      "Winston (Overwatch)",
      "Cortana",
      "GLaDOS",
      "Duke Nukem",
      "Marcus Fenix",
      "Sora (Kingdom Hearts)",
      "Arthur Morgan",
      "Trevor Philips",
      "CJ (GTA: San Andreas)",
      "Vault Boy",
      "Bayonetta",
      "Ratchet",
      "Clank",
      "Banjo-Kazooie",
      "Toad",
      "Isabelle (Animal Crossing)",
      "Tom Nook",
      "Princess Daisy",
      "Wario",
      "Waluigi",
      "Jill Valentine",
      "Leon Kennedy",
      "Aloy (Horizon Zero Dawn)",
      "Dante (Devil May Cry)",
      "Sephiroth",
      "Mewtwo",
      "Ash Ketchum",
      "Luigi",
      "Joker (Persona 5)",
      "Zangief",
      "Vault-Tec",
      "Big Daddy (BioShock)",
      "Little Sister (BioShock)",
      "Commander Shepard",
      "Max Payne",
      "Rayman",
      "Pit (Kid Icarus)",
      "Ganondorf",
      "Marcus Holloway (Watch Dogs 2)",
      "Sam Fisher (Splinter Cell)",
      "Shovel Knight",
      "Q*bert",
      "Earthworm Jim",
      "Captain Price",
      "Soap MacTavish",
      "Aiden Pearce (Watch Dogs)",
      "Handsome Jack (Borderlands)",
      "Cuphead",
      "King Dedede",
      "Meta Knight",
      "K.K. Slider",
      "Spy (Team Fortress 2)",
      "Heavy (Team Fortress 2)",
      "The Prince (Katamari)",
      "Altair (Assassin's Creed)",
      "Cole MacGrath (Infamous)",
      "Crash (Crash Bandicoot)",
      "Conker",
      "Phoenix Wright",
      "Professor Layton",
    ],
  },
  {
    title: "Food and Drink",
    description:
      "Popular foods, dishes, drinks, and cuisines from around the world.",
    cards: [
      "Pizza",
      "Sushi",
      "Burger",
      "Tacos",
      "Pasta",
      "Steak",
      "Ice Cream",
      "Coffee",
      "Tea",
      "Chocolate Cake",
      "Fried Chicken",
      "Hot Dog",
      "Milkshake",
      "Paella",
      "Dim Sum",
      "Burrito",
      "Pho",
      "Croissant",
      "Cheesecake",
      "Margarita",
      "Nachos",
      "Salad",
      "Ramen",
      "Falafel",
      "Pancakes",
      "Dumplings",
      "Apple Pie",
      "Bagel",
      "Waffles",
      "Lasagna",
      "Curry",
      "Sashimi",
      "Cupcake",
      "Donuts",
      "Quesadilla",
      "Gazpacho",
      "Churros",
      "Oysters",
      "BBQ Ribs",
      "Hummus",
      "Guacamole",
      "Sausages",
      "Risotto",
      "Kimchi",
      "Samosa",
      "Smoothie",
      "Spring Rolls",
      "Fondue",
      "Macarons",
      "Bibimbap",
      "Egg Rolls",
      "Fish and Chips",
      "Bruschetta",
      "Tiramisu",
      "French Fries",
      "Empanada",
      "Crepe",
      "Gelato",
      "Baklava",
      "Poutine",
      "Pretzel",
      "Cappuccino",
      "Cheese Plate",
      "Gyoza",
      "Tapas",
      "Cheeseburger",
      "Veggie Burger",
      "Fajitas",
      "Bubble Tea",
      "Espresso",
      "Mashed Potatoes",
      "Popcorn",
      "Jambalaya",
      "Ratatouille",
      "Pad Thai",
      "Clam Chowder",
      "Shawarma",
      "Chicken Wings",
      "Eggnog",
      "Meatballs",
      "Caesar Salad",
      "Hot Chocolate",
      "Banana Split",
      "Gingerbread",
      "Mochi",
      "Cannoli",
      "Chili Con Carne",
      "Boba Tea",
      "Eclair",
      "Tempura",
      "Ceviche",
      "Moussaka",
      "Pierogi",
      "Gumbo",
      "Taco Salad",
      "Coleslaw",
      "Pumpkin Pie",
      "Baked Alaska",
      "Sangria",
    ],
  },
  {
    title: "Famous Landmarks",
    description:
      "World-famous structures, buildings, monuments, and natural wonders.",
    cards: [
      "Eiffel Tower",
      "Statue of Liberty",
      "Great Wall of China",
      "Colosseum",
      "Taj Mahal",
      "Big Ben",
      "Sydney Opera House",
      "Christ the Redeemer",
      "Machu Picchu",
      "Stonehenge",
      "Golden Gate Bridge",
      "Burj Khalifa",
      "Niagara Falls",
      "Mount Rushmore",
      "Grand Canyon",
      "Leaning Tower of Pisa",
      "Pyramids of Giza",
      "Angkor Wat",
      "Acropolis of Athens",
      "Forbidden City",
      "Mount Fuji",
      "Empire State Building",
      "Buckingham Palace",
      "Louvre Museum",
      "Petra",
      "St. Basil's Cathedral",
      "Hagia Sophia",
      "Great Barrier Reef",
      "Alhambra",
      "Brandenburg Gate",
      "Tower of London",
      "Versailles Palace",
      "Mount Everest",
      "Space Needle",
      "Arc de Triomphe",
      "Berlin Wall",
      "CN Tower",
      "Hoover Dam",
      "Sagrada Familia",
      "Edinburgh Castle",
      "Chichen Itza",
      "Burj Al Arab",
      "Uluru",
      "Parthenon",
      "Santorini",
      "Yellowstone National Park",
      "Hollywood Sign",
      "Panama Canal",
      "Trevi Fountain",
      "Table Mountain",
      "Notre-Dame Cathedral",
      "Pompeii",
      "Lake Baikal",
      "Victoria Falls",
      "Palace of Westminster",
      "Mount Kilimanjaro",
      "Great Sphinx of Giza",
      "Mont Saint-Michel",
      "Himeji Castle",
      "Red Square",
      "White House",
      "Serengeti",
      "Guggenheim Museum",
      "Bryce Canyon",
      "Potala Palace",
      "Blue Mosque",
      "Buckingham Fountain",
      "Gateway Arch",
      "The Shard",
      "Acadia National Park",
      "Wat Arun",
      "Horseshoe Bend",
      "Petronas Towers",
      "London Eye",
      "Banff National Park",
      "Terracotta Army",
      "Notre-Dame Basilica",
      "Mount Sinai",
      "Devils Tower",
      "Westminster Abbey",
      "Alcatraz Island",
      "Brooklyn Bridge",
      "Lotus Temple",
      "Florence Cathedral",
      "Capitol Hill",
      "Great Ocean Road",
      "Death Valley",
      "Mount Olympus",
      "Everglades National Park",
      "Luxor Temple",
      "Moai Statues",
      "Zion National Park",
      "Lascaux Caves",
      "Prague Castle",
      "Mount Etna",
      "Giant's Causeway",
    ],
  },
  {
    title: "Sports Stars",
    description:
      "Athletes from various sports recognized for their talent and achievements.",
    cards: [
      "Michael Jordan",
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Serena Williams",
      "LeBron James",
      "Tiger Woods",
      "Roger Federer",
      "Usain Bolt",
      "Muhammad Ali",
      "Tom Brady",
      "Simone Biles",
      "Kobe Bryant",
      "Rafael Nadal",
      "Lewis Hamilton",
      "Sachin Tendulkar",
      "Michael Phelps",
      "Wayne Gretzky",
      "Pele",
      "Shaquille O'Neal",
      "Neymar",
      "Megan Rapinoe",
      "Virat Kohli",
      "Stephen Curry",
      "Conor McGregor",
      "Mike Tyson",
      "Novak Djokovic",
      "Diego Maradona",
      "David Beckham",
      "Floyd Mayweather",
      "Zinedine Zidane",
      "Cristiano Ronaldo Jr.",
      "Alex Morgan",
      "Kevin Durant",
      "Magic Johnson",
      "Derek Jeter",
      "Kylian Mbappé",
      "Maria Sharapova",
      "Patrick Mahomes",
      "Simone Manuel",
      "Andy Murray",
      "Gabby Douglas",
      "Dwayne Johnson",
      "Sidney Crosby",
      "Venus Williams",
      "Eliud Kipchoge",
      "Canelo Alvarez",
      "Naomi Osaka",
      "Tony Hawk",
      "Aaron Rodgers",
      "Ronda Rousey",
      "Chris Froome",
      "Phil Mickelson",
      "Hope Solo",
      "James Harden",
      "Lindsey Vonn",
      "Zlatan Ibrahimović",
      "Katie Ledecky",
      "Peyton Manning",
      "Dirk Nowitzki",
      "Russell Wilson",
      "Gareth Bale",
      "Yao Ming",
      "Steph Gilmore",
      "Marta Vieira da Silva",
      "George Foreman",
      "Lance Armstrong",
      "Albert Pujols",
      "Anderson Silva",
      "Ronaldinho",
      "Alex Ovechkin",
      "Ichiro Suzuki",
      "Evander Holyfield",
      "Michelle Kwan",
      "Floyd Patterson",
      "Barry Bonds",
      "Jackie Joyner-Kersee",
      "Fernando Alonso",
      "Michael Schumacher",
      "Jerry Rice",
      "Wilt Chamberlain",
      "Joe Montana",
      "Greg Norman",
      "Danica Patrick",
      "Carl Lewis",
      "Thierry Henry",
      "Jon Jones",
      "Oscar De La Hoya",
      "Toni Kroos",
      "Babe Ruth",
      "Dominique Dawes",
      "Ryan Lochte",
      "Ben Roethlisberger",
      "Travis Pastrana",
      "Manny Pacquiao",
      "Fernando Torres",
    ],
  },
  {
    title: "Cartoon Characters",
    description:
      "Beloved animated characters from TV shows and movies, old and new.",
    cards: [
      "Mickey Mouse",
      "SpongeBob SquarePants",
      "Bugs Bunny",
      "Scooby-Doo",
      "Bart Simpson",
      "Elsa",
      "Daffy Duck",
      "Tom",
      "Jerry",
      "Woody",
      "Buzz Lightyear",
      "Dora the Explorer",
      "Patrick Star",
      "Pikachu",
      "Homer Simpson",
      "Charlie Brown",
      "Garfield",
      "Tweety Bird",
      "Road Runner",
      "Shrek",
      "Popeye",
      "Fred Flintstone",
      "Cinderella",
      "Minnie Mouse",
      "Winnie the Pooh",
      "Olaf",
      "Aladdin",
      "Jasmine",
      "Donald Duck",
      "Dexter",
      "Powerpuff Girls",
      "Rapunzel",
      "Phineas",
      "Ferb",
      "Peter Griffin",
      "Stewie Griffin",
      "Rick Sanchez",
      "Morty Smith",
      "Princess Bubblegum",
      "Finn",
      "Jake",
      "Captain Planet",
      "Moana",
      "Tarzan",
      "Yogi Bear",
      "Batman",
      "Robin",
      "Ben 10",
      "Superman",
      "Elsa",
      "Anna",
      "Peppa Pig",
      "Arthur",
      "Bambi",
      "Betty Boop",
      "Ariel",
      "Goofy",
      "Cruella de Vil",
      "Goku",
      "Vegeta",
      "Naruto",
      "Ash Ketchum",
      "Squidward",
      "Ed, Edd n Eddy",
      "Hello Kitty",
      "Angelica Pickles",
      "Tommy Pickles",
      "Tinker Bell",
      "Pluto",
      "Baloo",
      "Simba",
      "Nemo",
      "Dory",
      "Buzz",
      "Jessie",
      "Wall-E",
      "Mr. Incredible",
      "Elastigirl",
      "Baymax",
      "Lightning McQueen",
      "Mater",
      "Merida",
      "Kung Fu Panda",
      "Megamind",
      "Gru",
      "Minions",
      "Stitch",
      "Tigger",
      "Rafiki",
      "Scar",
      "Mufasa",
      "Belle",
      "Beast",
      "Hiccup",
      "Toothless",
      "Casper",
      "Tintin",
      "Mulan",
      "Sleeping Beauty",
      "Snow White",
      "Puss in Boots",
    ],
  },
  {
    title: "Sci-Fi and Fantasy",
    description:
      "Characters, places, and objects from popular science fiction and fantasy stories.",
    cards: [
      "Harry Potter",
      "Darth Vader",
      "Frodo Baggins",
      "Gandalf",
      "Luke Skywalker",
      "Doctor Who",
      "Captain Kirk",
      "Spock",
      "Yoda",
      "Han Solo",
      "Princess Leia",
      "Indiana Jones",
      "Rick Deckard",
      "Ellen Ripley",
      "Neo",
      "Morpheus",
      "Trinity",
      "Thanos",
      "Iron Man",
      "Thor",
      "Captain America",
      "Wonder Woman",
      "Batman",
      "Superman",
      "Aquaman",
      "Black Widow",
      "Loki",
      "Chewbacca",
      "Rey",
      "Kylo Ren",
      "Katniss Everdeen",
      "Bilbo Baggins",
      "Jon Snow",
      "Daenerys Targaryen",
      "Arya Stark",
      "The Terminator",
      "Predator",
      "Xenomorph",
      "Groot",
      "Rocket Raccoon",
      "Spiderman",
      "Deadpool",
      "Wolverine",
      "Professor X",
      "Jean Grey",
      "Magneto",
      "Storm",
      "Cyclops",
      "Hagrid",
      "Dumbledore",
      "Severus Snape",
      "Ron Weasley",
      "Hermione Granger",
      "Voldemort",
      "Bellatrix Lestrange",
      "Sauron",
      "Gollum",
      "Legolas",
      "Aragorn",
      "E.T.",
      "Robocop",
      "Wall-E",
      "Buzz Lightyear",
      "Captain Marvel",
      "Star-Lord",
      "Drax",
      "Gamora",
      "Doctor Strange",
      "Black Panther",
      "Vision",
      "Scarlet Witch",
      "Silver Surfer",
      "Green Lantern",
      "Flash",
      "Green Arrow",
      "Harley Quinn",
      "Joker",
      "Boba Fett",
      "Jabba the Hutt",
      "Obi-Wan Kenobi",
      "Padmé Amidala",
      "Ash Ketchum",
      "Pikachu",
      "Godzilla",
      "King Kong",
      "Blade Runner",
      "Optimus Prime",
      "Megatron",
      "Buffy Summers",
      "Edward Cullen",
      "Bella Swan",
      "Alita",
      "Zorro",
      "Westley (The Princess Bride)",
      "Dracula",
      "Frankenstein's Monster",
      "The Invisible Man",
      "Werewolf",
      "Selene (Underworld)",
      "Van Helsing",
    ],
  },
  {
    title: "Mythology & Legends",
    description:
      "Gods, heroes, mythical creatures, and legends from various cultures.",
    cards: [
      "Zeus",
      "Poseidon",
      "Hades",
      "Hercules",
      "Achilles",
      "Thor",
      "Odin",
      "Loki",
      "Anubis",
      "Ra",
      "Isis",
      "Osiris",
      "Horus",
      "Medusa",
      "Apollo",
      "Artemis",
      "Athena",
      "Ares",
      "Hermes",
      "Persephone",
      "Demeter",
      "Dionysus",
      "Cronus",
      "Gaia",
      "Pandora",
      "Gilgamesh",
      "Beowulf",
      "King Arthur",
      "Merlin",
      "Lancelot",
      "Guinevere",
      "Robin Hood",
      "Excalibur",
      "Kraken",
      "Minotaur",
      "Cyclops",
      "Centaur",
      "Sphinx",
      "Cerberus",
      "Phoenix",
      "Pegasus",
      "Hydra",
      "Basilisk",
      "Yeti",
      "Bigfoot",
      "Chupacabra",
      "Dragon",
      "Quetzalcoatl",
      "Sun Wukong",
      "Bastet",
      "Fenrir",
      "Freya",
      "Valkyries",
      "Maui",
      "Anansi",
      "Ganesha",
      "Shiva",
      "Vishnu",
      "Krishna",
      "Hanuman",
      "Rama",
      "Buddha",
      "Confucius",
      "Susanoo",
      "Amaterasu",
      "Kitsune",
      "Raijin",
      "Fujin",
      "Jormungandr",
      "Balder",
      "Hel",
      "Skadi",
      "Frigg",
      "Yggdrasil",
      "Cú Chulainn",
      "Fionn mac Cumhaill",
      "Morrigan",
      "Dagda",
      "Baba Yaga",
      "Koschei",
      "Lilith",
      "Lucifer",
      "Michael (Archangel)",
      "Raphael (Archangel)",
      "Gabriel (Archangel)",
      "Uriel (Archangel)",
      "Vampire",
      "Werewolf",
      "Griffin",
      "Chimera",
      "Nemean Lion",
      "Manticore",
      "Golem",
      "Leviathan",
      "Selkie",
      "Banshee",
      "Kappa",
      "Wendigo",
      "Jackalope",
    ],
  },
  {
    title: "Pop Songs & Bands",
    description:
      "Popular bands, artists, songs, and lyrics from various eras of pop music.",
    cards: [
      "Thriller - Michael Jackson",
      "Like a Virgin - Madonna",
      "Shape of You - Ed Sheeran",
      "Bohemian Rhapsody - Queen",
      "Rolling in the Deep - Adele",
      "Billie Jean - Michael Jackson",
      "Poker Face - Lady Gaga",
      "Wannabe - Spice Girls",
      "Uptown Funk - Bruno Mars",
      "Firework - Katy Perry",
      "Baby One More Time - Britney Spears",
      "Hey Ya! - Outkast",
      "Shake It Off - Taylor Swift",
      "Single Ladies - Beyoncé",
      "Happy - Pharrell Williams",
      "Blinding Lights - The Weeknd",
      "Viva la Vida - Coldplay",
      "Bad Guy - Billie Eilish",
      "Can't Stop the Feeling - Justin Timberlake",
      "Titanium - David Guetta",
      "Chandelier - Sia",
      "Roar - Katy Perry",
      "Toxic - Britney Spears",
      "Love Story - Taylor Swift",
      "Backstreet Boys",
      "NSYNC",
      "ABBA",
      "The Beatles",
      "Maroon 5",
      "Imagine Dragons",
      "One Direction",
      "BTS",
      "Blackpink",
      "Justin Bieber",
      "Selena Gomez",
      "Ariana Grande",
      "Nicki Minaj",
      "Eminem",
      "Lady Gaga",
      "Rihanna",
      "Post Malone",
      "Dua Lipa",
      "Shawn Mendes",
      "Miley Cyrus",
      "Cardi B",
      "Coldplay",
      "Green Day",
      "Linkin Park",
      "Beyoncé",
      "Drake",
      "Ed Sheeran",
      "Adele",
      "Queen",
      "Michael Jackson",
      "Madonna",
      "Fleetwood Mac",
      "Nirvana",
      "Taylor Swift",
      "Kanye West",
      "Britney Spears",
      "Jennifer Lopez",
      "Christina Aguilera",
      "Prince",
      "Whitney Houston",
      "Mariah Carey",
      "Elvis Presley",
      "David Bowie",
      "Pink",
      "Bruno Mars",
      "Jay-Z",
      "Snoop Dogg",
      "Avicii",
      "Ed Sheeran",
      "Sam Smith",
      "Katy Perry",
      "Twenty One Pilots",
      "Imagine - John Lennon",
      "Hotel California - Eagles",
      "Sweet Child o' Mine - Guns N' Roses",
      "Wonderwall - Oasis",
      "Hey Jude - The Beatles",
      "Stairway to Heaven - Led Zeppelin",
      "Africa - Toto",
      "Let It Be - The Beatles",
      "Havana - Camila Cabello",
      "Senorita - Shawn Mendes & Camila Cabello",
      "Gangnam Style - Psy",
      "Despacito - Luis Fonsi",
      "Old Town Road - Lil Nas X",
    ],
  },
];
