export const decks = [
  {
    title: "Blockbuster Movies",
    description:
      "Act out or describe iconic blockbuster films that made cinema history.",
    cards: [
      "Titanic",
      "Jurassic Park",
      "The Avengers",
      "Avatar",
      "Star Wars: A New Hope",
      "Inception",
      "The Lion King",
      "Forrest Gump",
      "The Dark Knight",
      "Back to the Future",
      "Jaws",
      "The Matrix",
      "Toy Story",
      "Frozen",
      "Harry Potter and the Sorcerer's Stone",
      "Finding Nemo",
      "The Godfather",
      "Pirates of the Caribbean",
      "E.T.",
      "Rocky",
      "Ghostbusters",
      "Home Alone",
      "Indiana Jones",
      "The Shawshank Redemption",
      "Iron Man",
      "The Lord of the Rings: Fellowship of the Ring",
      "The Hunger Games",
      "Black Panther",
      "Coco",
      "Wonder Woman",
      "Spider-Man",
      "The Incredibles",
      "Up",
      "Interstellar",
      "Shrek",
      "Beauty and the Beast",
      "Gladiator",
      "Terminator 2",
      "Die Hard",
      "Mad Max: Fury Road",
      "Pulp Fiction",
      "Guardians of the Galaxy",
      "Braveheart",
      "Men in Black",
      "Twilight",
      "Avatar: The Way of Water",
      "Deadpool",
      "The Fast and the Furious",
      "Aladdin",
      "WALL-E",
      "Zootopia",
      "The Silence of the Lambs",
      "Titanic",
      "Mission: Impossible",
      "Skyfall",
      "Casino Royale",
      "Monsters, Inc.",
      "Kung Fu Panda",
      "Moana",
      "Despicable Me",
      "Inside Out",
      "Aquaman",
      "Jurassic World",
      "Transformers",
      "Logan",
      "Dunkirk",
      "Parasite",
      "Joker",
      "Captain Marvel",
      "La La Land",
      "A Star is Born",
      "Thor: Ragnarok",
      "Venom",
      "Shazam!",
      "Mulan",
      "Star Wars: The Force Awakens",
      "Avengers: Endgame",
      "Avengers: Infinity War",
      "Star Wars: The Empire Strikes Back",
      "Harry Potter and the Deathly Hallows",
      "Ant-Man",
      "The Great Gatsby",
      "X-Men",
      "Fantastic Beasts",
      "The Revenant",
      "Frozen II",
      "Toy Story 3",
      "Jumanji",
      "King Kong",
      "The Hobbit",
      "Armageddon",
      "Twister",
      "The Departed",
      "Gravity",
      "300",
      "Spider-Man: No Way Home",
      "Doctor Strange",
      "Justice League",
      "Batman Begins",
      "Man of Steel",
      "Top Gun",
      "The Little Mermaid",
      "Raiders of the Lost Ark",
      "Star Trek",
      "Pacific Rim",
    ],
  },
  {
    title: "Harry Potter Universe",
    description:
      "Characters, spells, magical items, and locations from the wizarding world of Harry Potter.",
    cards: [
      "Harry Potter",
      "Hermione Granger",
      "Ron Weasley",
      "Albus Dumbledore",
      "Severus Snape",
      "Voldemort",
      "Sirius Black",
      "Draco Malfoy",
      "Dobby",
      "Hagrid",
      "Ginny Weasley",
      "Luna Lovegood",
      "Neville Longbottom",
      "Minerva McGonagall",
      "Lucius Malfoy",
      "Bellatrix Lestrange",
      "Fred Weasley",
      "George Weasley",
      "Cedric Diggory",
      "Cho Chang",
      "Dolores Umbridge",
      "Remus Lupin",
      "Nymphadora Tonks",
      "Arthur Weasley",
      "Molly Weasley",
      "Fawkes",
      "Nagini",
      "Basilisk",
      "Buckbeak",
      "Sorting Hat",
      "Elder Wand",
      "Invisibility Cloak",
      "Resurrection Stone",
      "Golden Snitch",
      "Nimbus 2000",
      "Firebolt",
      "Platform 9¾",
      "Diagon Alley",
      "Gringotts Bank",
      "Hogwarts Express",
      "Hogwarts Castle",
      "Forbidden Forest",
      "The Burrow",
      "Quidditch",
      "Polyjuice Potion",
      "Marauder's Map",
      "Patronus Charm",
      "Expelliarmus",
      "Avada Kedavra",
      "Expecto Patronum",
      "Lumos",
      "Wingardium Leviosa",
      "Sectumsempra",
      "Cruciatus Curse",
      "Imperius Curse",
      "Azkaban",
      "Death Eaters",
      "Dementors",
      "Goblet of Fire",
      "Triwizard Tournament",
      "Order of the Phoenix",
      "Mirror of Erised",
      "Room of Requirement",
      "Whomping Willow",
      "Pensieve",
      "Horcrux",
      "Chamber of Secrets",
      "Philosopher's Stone",
      "Time-Turner",
      "Butterbeer",
      "Chocolate Frog",
      "Floo Powder",
      "Knight Bus",
      "Mad-Eye Moody",
      "Gilderoy Lockhart",
      "Cornelius Fudge",
      "Kingsley Shacklebolt",
      "Peter Pettigrew",
      "Grawp",
      "Crookshanks",
      "Scabbers",
      "Hedwig",
      "Mandrake",
      "Thestral",
      "Veela",
      "Werewolf",
      "House-Elf",
      "Deathly Hallows",
      "Durmstrang",
      "Beauxbatons",
      "Godric Gryffindor",
      "Salazar Slytherin",
      "Rowena Ravenclaw",
      "Helga Hufflepuff",
      "Nearly Headless Nick",
      "Moaning Myrtle",
      "Filch",
      "Peeves",
    ],
  },
  {
    title: "Disney Classics",
    description:
      "Beloved characters, songs, and moments from classic Disney movies.",
    cards: [
      "Mickey Mouse",
      "Donald Duck",
      "Cinderella",
      "Snow White",
      "Ariel",
      "Simba",
      "Elsa",
      "Anna",
      "Belle",
      "Beast",
      "Peter Pan",
      "Tinker Bell",
      "Pinocchio",
      "Bambi",
      "Dumbo",
      "Aladdin",
      "Genie",
      "Mulan",
      "Pocahontas",
      "Rapunzel",
      "Sleeping Beauty",
      "Maleficent",
      "Cruella de Vil",
      "Woody",
      "Buzz Lightyear",
      "Timon",
      "Pumbaa",
      "Ursula",
      "Jasmine",
      "Prince Charming",
      "Tarzan",
      "Jane",
      "Alice in Wonderland",
      "Cheshire Cat",
      "Olaf",
      "Kristoff",
      "Moana",
      "Maui",
      "Lilo",
      "Stitch",
      "Goofy",
      "Pluto",
      "Chip 'n' Dale",
      "Scar",
      "Merida",
      "Sebastian",
      "Flounder",
      "Gaston",
      "Lumière",
      "Cogsworth",
      "Dory",
      "Nemo",
      "Marlin",
      "Lady",
      "Tramp",
      "101 Dalmatians",
      "Hercules",
      "Megara",
      "Robin Hood",
      "Winnie the Pooh",
      "Eeyore",
      "Piglet",
      "Tigger",
      "Baloo",
      "Mowgli",
      "King Louie",
      "Esmeralda",
      "Quasimodo",
      "Captain Hook",
      "Mary Poppins",
      "Baymax",
      "Joy",
      "Sadness",
      "Mike Wazowski",
      "Sully",
      "Mater",
      "Lightning McQueen",
      "Peter Pan's Shadow",
      "Thumper",
      "Jiminy Cricket",
      "Fairy Godmother",
      "Zazu",
      "Aurora",
      "Pocahontas",
      "Daisy Duck",
      "Flynn Rider",
      "Pascal",
      "Mother Gothel",
      "Prince Eric",
      "Flora, Fauna, and Merryweather",
      "The Seven Dwarfs",
      "The Incredibles",
      "Jack Skellington",
      "Oogie Boogie",
      "Kuzco",
      "Yzma",
      "Bolt",
      "Remy",
      "WALL-E",
      "EVE",
    ],
  },
  {
    title: "Marvel Heroes & Villains",
    description:
      "Superheroes and villains from the expansive Marvel Comics and Cinematic Universe.",
    cards: [
      "Iron Man",
      "Captain America",
      "Thor",
      "Hulk",
      "Black Widow",
      "Hawkeye",
      "Spider-Man",
      "Black Panther",
      "Doctor Strange",
      "Scarlet Witch",
      "Vision",
      "Captain Marvel",
      "Falcon",
      "Winter Soldier",
      "Ant-Man",
      "Wasp",
      "Star-Lord",
      "Gamora",
      "Rocket Raccoon",
      "Groot",
      "Drax",
      "Loki",
      "Thanos",
      "Ultron",
      "Green Goblin",
      "Doctor Octopus",
      "Venom",
      "Deadpool",
      "Daredevil",
      "Luke Cage",
      "Jessica Jones",
      "Iron Fist",
      "Kingpin",
      "Punisher",
      "Ghost Rider",
      "Magneto",
      "Professor X",
      "Jean Grey",
      "Cyclops",
      "Storm",
      "Mystique",
      "Nightcrawler",
      "Beast",
      "Quicksilver",
      "Silver Surfer",
      "Blade",
      "Shang-Chi",
      "Moon Knight",
      "She-Hulk",
      "Ms. Marvel",
      "War Machine",
      "Nebula",
      "Yondu",
      "Mantis",
      "Nick Fury",
      "Agent Coulson",
      "Red Skull",
      "Hydra Agent",
      "Ego",
      "The Collector",
      "Ronan the Accuser",
      "Killmonger",
      "Vulture",
      "Electro",
      "Sandman",
      "Rhino",
      "Carnage",
      "Morbius",
      "Sabretooth",
      "Juggernaut",
      "Apocalypse",
      "Cable",
      "Gambit",
      "Rogue",
      "Emma Frost",
      "Colossus",
      "Angel",
      "Iceman",
      "Polaris",
      "Black Cat",
      "Kraven the Hunter",
      "Taskmaster",
      "Dormammu",
      "Hela",
      "Surtur",
      "Crossbones",
      "Baron Zemo",
      "America Chavez",
      "Kate Bishop",
      "Agatha Harkness",
      "Namor",
      "Wong",
      "Shuri",
      "Okoye",
      "Abomination",
      "Adam Warlock",
      "MODOK",
      "Lady Sif",
      "Heimdall",
      "Howard the Duck",
    ],
  },
  {
    title: "90s Throwbacks",
    description:
      "Nostalgic references including music, TV shows, toys, and trends from the 1990s.",
    cards: [
      "Tamagotchi",
      "Spice Girls",
      "Blockbuster Video",
      "Friends",
      "Fresh Prince of Bel-Air",
      "Britney Spears",
      "Beanie Babies",
      "Pokemon",
      "Furbies",
      "Walkman",
      "Game Boy",
      "AOL Dial-Up",
      "Titanic",
      "Saved by the Bell",
      "The Macarena",
      "Sega Genesis",
      "Snap Bracelets",
      "The Lion King",
      "Jurassic Park",
      "Boy Meets World",
      "Nintendo 64",
      "Skip-It",
      "NSYNC",
      "Backstreet Boys",
      "MC Hammer",
      "Power Rangers",
      "Lisa Frank",
      "Clueless",
      "Super Soaker",
      "Slap Bracelets",
      "Full House",
      "Goosebumps",
      "Tickle Me Elmo",
      "Polly Pocket",
      "Discman",
      "The Simpsons",
      "Floppy Disks",
      "Sabrina the Teenage Witch",
      "TRL (Total Request Live)",
      "Dawson's Creek",
      "Pogs",
      "Space Jam",
      "MTV",
      "Baywatch",
      "Pulp Fiction",
      "Rollerblades",
      "Jumanji",
      "Home Alone",
      "Giga Pets",
      "Buffy the Vampire Slayer",
      "Nokia 3310",
      "Ring Pop",
      "Xena: Warrior Princess",
      "Mighty Ducks",
      "Slime",
      "Hip Hop Dance",
      "The X-Files",
      "Gel Pens",
      "The Matrix",
      "Scrunchies",
      "Cargo Pants",
      "Platform Shoes",
      "Surge Soda",
      "Clarissa Explains It All",
      "Animaniacs",
      "Hey Arnold!",
      "Doug",
      "Rocko's Modern Life",
      "Are You Afraid of the Dark?",
      "Mario Kart 64",
      "Windows 95",
      "Dunkaroos",
      "Dial-Up Internet",
      "Fanny Packs",
      "Yo-Yos",
      "Hacky Sack",
      "Reebok Pumps",
      "Cassette Tapes",
      "Grunge Music",
      "Doc Martens",
      "Trapper Keeper",
      "Waterbeds",
      "Pagers",
      "Air Jordans",
      "Laser Pointers",
      "Mortal Kombat",
      "Street Fighter",
      "Go-Gurt",
      "Baggy Jeans",
      "Sony PlayStation",
      "Easy-Bake Oven",
      "Lite-Brite",
      "Moon Shoes",
      "Teenage Mutant Ninja Turtles",
      "The Oregon Trail",
      "Lunchables",
      "Butterfly Clips",
      "Dance Dance Revolution",
      "Mr. Sketch Markers",
      "Nickelodeon Slime",
      "Inspector Gadget",
    ],
  },
  {
    title: "Animal Kingdom",
    description:
      "Animals of all shapes and sizes, from pets to wild beasts across the globe.",
    cards: [],
  },
  {
    title: "Iconic Celebrities",
    description:
      "Famous actors, singers, influencers, and personalities recognizable worldwide.",
    cards: [],
  },
  {
    title: "Video Game Legends",
    description:
      "Characters, game titles, and iconic elements from classic and contemporary video games.",
    cards: [],
  },
  {
    title: "Food and Drink",
    description:
      "Popular foods, dishes, drinks, and cuisines from around the world.",
    cards: [],
  },
  {
    title: "Netflix Originals",
    description:
      "Characters, series, and films produced exclusively by Netflix.",
    cards: [],
  },
  {
    title: "Famous Landmarks",
    description:
      "World-famous structures, buildings, monuments, and natural wonders.",
    cards: [],
  },
  {
    title: "Sports Stars",
    description:
      "Athletes from various sports recognized for their talent and achievements.",
    cards: [],
  },
  {
    title: "Cartoon Characters",
    description:
      "Beloved animated characters from TV shows and movies, old and new.",
    cards: [],
  },
  {
    title: "Musical Instruments",
    description:
      "Instruments from classical to contemporary music, including common and obscure ones.",
    cards: [],
  },
  {
    title: "Sci-Fi and Fantasy",
    description:
      "Characters, places, and objects from popular science fiction and fantasy stories.",
    cards: [],
  },
  {
    title: "Mythology & Legends",
    description:
      "Gods, heroes, mythical creatures, and legends from various cultures.",
    cards: [],
  },
  {
    title: "Superheroes & Sidekicks",
    description:
      "Pairs and duos of famous superheroes and their loyal sidekicks.",
    cards: [],
  },
  {
    title: "Brands & Logos",
    description:
      "Famous brands, products, and logos easily recognized around the globe.",
    cards: [],
  },
  {
    title: "Pop Songs & Bands",
    description:
      "Popular bands, artists, songs, and lyrics from various eras of pop music.",
    cards: [],
  },
  {
    title: "World Holidays & Celebrations",
    description:
      "Festivals, holidays, and celebrations from different countries and cultures worldwide.",
    cards: [],
  },
];
